home/urls.py
from django.conf.urls import url

from . import views

app_name = 'home'


urlpatterns = [

    # / - Home Page
    url(r'^$', views.home_page, name='home_page'),
    # orders page
    url(r'^orders/$', views.orders, name='orders'),
    # /get_customer
    url(r'^clothwise/$', views.clothwise, name='clothwise'),
    # /get_customer
    url(r'^expenses/$', views.expenses, name='expenses'),
    # /get_customer
    url(r'^get_customer/$', views.get_customer, name='get_customer'),
    # /get_reports
    url(r'^reports/$', views.get_reports, name='get_reports'),
    # /new_order
    url(r'^new_order/(?P<customer_id>[0-9]+)/$', views.new_order, name='new_order'),
    # / register customer
    url(r'^register_customer/$', views.customer_registration, name='register_customer'),
    # /change_status
    url(r'^change_status/$', views.change_status, name='change_status'),
    # / register customer
    url(r'^daywise_excel/$', views.day_excel, name='daywise_excel'),
    # / General Excel
    url(r'^general_excel/(?P<type>[\w]+)$', views.general_excel, name='general_excel'),
    url(r'^general_excel/$', views.general_excel, name='general_excel'),

    url(r'^download_receipt/(?P<pk>[0-9]+)/$', views.download_receipt, name='download_receipt'),
]

washing/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^', include('home.urls')),
]

home/models.py
from django.contrib.auth.models import User
from django.db import models

from home.email_sender import send_email


# Create your models here.


class UserDetails(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)


class Customer(models.Model):
    name = models.CharField(max_length=200, null=False)
    mobile = models.CharField(max_length=10)
    email = models.EmailField(null=True, blank=True)
    address = models.CharField(max_length=500, null=True, blank=True)
    is_active = models.BooleanField(default=True)
    # date_created = models.DateField()


class Order(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    token = models.IntegerField()
    # user = models.ForeignKey(UserDetails, on_delete=models.CASCADE, null=True)
    kg = models.DecimalField(max_digits=6, decimal_places=2)
    received_date = models.DateTimeField()
    delivery_date = models.DateTimeField(null=True, blank=True)
    price = models.FloatField()
    status = models.IntegerField(default=1)
    is_active = models.BooleanField(default=True)

    def save(self, *args, **kwargs):
        super(Order, self).save(*args, **kwargs)
        subject = ''
        msg = ''
        if self.status == 1:
            subject = 'Order Received'
            msg = '<b>Order Details:</b><br>' \
                  'Total Weight: ' + str(self.kg) + '<br>Price: ' + str(self.price)
        elif self.status == 2:
            subject = 'Order Details'
            msg = '<b>Order Details:</b><br>' \
                  'Order No: ' + str(self.pk) + '<br>Total Weight: ' + str(self.kg) + ' Kg<br>Price: ' + str(self.price) \
                  + '<br><b>Clothes Type</b><br>'
            tmp = ''
            for each in self.orderdetail_set.all():
                if each.count > 0:
                    tmp += each.category.name + ': ' + str(each.count) + '<br>'
            msg += tmp
        elif self.status == 3:
            subject = 'Order Pick-up Reminder'
            msg = 'Order Details<br>' \
                  'Order No: ' + str(self.pk) + '<br>Total Weight: ' + str(self.kg) + ' Kg<br>Price: ' + str(
                self.price) + '<br>Order No: ' + str(self.pk) \
                  + '<br><br>Your order has been successfully washed. Kindly collect your clothes from Wool World.<br>' \
                  + '<br>Hope to be at your service again.'
        elif self.status == 4:
            subject = 'Order Delivered'
            msg = 'Order Details<br>' \
                  'Order No: ' + str(self.pk) + '<br>Total Weight: ' + str(self.kg) + ' Kg<br>Price: ' + str(self.price) \
                  + '<br>Your order has been successfully delivered on <br>' + (
                      self.delivery_date.strftime('%d %m %y, %I %M %p')) \
                  + '<br><br>Hope to be at your service again.'

        send_email(self.customer.email, subject, msg)
        price = self.price
        date = self.delivery_date
        if date:
            money_obj = Money.objects.filter(date=date)
            if len(money_obj) > 0:
                money_obj = money_obj[0]
                money_obj.total_income += price
            else:
                Money.objects.create(date=date, total_income=price)


# 1: only kg
# 2: clothwise
# 3: completed washing
# 4: delivered

class Category(models.Model):
    name = models.CharField(max_length=100)
    # to_show = models.BooleanField(default=True)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.name


class OrderDetail(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.DO_NOTHING)
    count = models.IntegerField(default=0)

    def __str__(self):
        return self.category.name + ' ' + str(self.count)


class Price(models.Model):
    kg = models.DecimalField(max_digits=6, decimal_places=2)
    cost = models.FloatField()


class Expense(models.Model):
    name = models.CharField(max_length=50)
    description = models.CharField(max_length=200, null=True, blank=True)
    date = models.DateField()
    cost = models.FloatField()

    def save(self, *args, **kwargs):
        super(Expense, self).save(*args, **kwargs)
        # print('called')
        cost = self.cost
        date = self.date
        money_obj = Money.objects.filter(date=date)
        if len(money_obj) > 0:
            money_obj = money_obj[0]
            money_obj.total_expenditure += cost
        else:
            Money.objects.create(date=date, total_expenditure=cost)


class Money(models.Model):
    date = models.DateField(unique=True)
    total_income = models.FloatField(default=0)
    total_expenditure = models.FloatField(default=0)

home/views.py
import datetime
import json
import mimetypes
import os
import shutil
from collections import OrderedDict

import openpyxl
from django.db.models import Q
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.utils.encoding import smart_str
from openpyxl import Workbook

from home.models import Customer, Price, Order, Category, OrderDetail, Expense
from home.models import Money
from washing.settings import MEDIA_ROOT


def order_to_dict(order):
    return {'name': order.customer.name, 'mobile': order.customer.mobile,
            'customer_pk': order.customer.pk,
            'received_date': str(
                order.received_date.strftime('%Y-%m-%d %I:%M %p')) if order.received_date is not None else 'N.A.',
            'delivery_date': str(
                order.delivery_date.strftime('%Y-%m-%d %I:%M %p')) if order.delivery_date is not None else 'N.A.',
            'order_pk': order.pk, 'price': str(order.price), 'kg': str(order.kg), 'status': order.status,
            'address': order.customer.address}


def home_page(request):
    if request.is_ajax():
        orders = Order.objects.filter(is_active=True).order_by('-received_date')
        dict = {
            'received_order': {},
            'clothwise_order': {},
            'washed_order': {}
        }

        for each in orders.filter(status=1):
            dict['received_order'][str(each.pk)] = order_to_dict(each)
        for each in orders.filter(status=2):
            dict['clothwise_order'][str(each.pk)] = order_to_dict(each)
        for each in orders.filter(status=3):
            dict['washed_order'][str(each.pk)] = order_to_dict(each)
            # for each in orders.filter(status=4):
            #     dict['delivered_order_' + each.pk] = serializers.serialize('json', each)

        json_ = json.dumps(dict)
        return HttpResponse(json_)
    else:
        cats = Category.objects.filter(is_active=True).values_list('name', flat=True)

        orders = Order.objects.filter(is_active=True).order_by('-received_date')

        return render(request, 'dashboard.html', {'received_orders': orders.filter(status=1),
                                                  'clothwise_orders': orders.filter(status=2),
                                                  'washed_orders': orders.filter(status=3),
                                                  'delivered_orders': orders.filter(status=4,
                                                                                    received_date__range=(
                                                                                        datetime.datetime.now() - datetime.timedelta(
                                                                                            2),
                                                                                        datetime.datetime.now())),
                                                  'category': [cats[i:i + 2] for i in range(0, len(cats), 2)]})


def get_customer(request):
    if request.is_ajax():
        if request.POST.get('query'):
            query = request.POST.get('query')
            all_cust = Customer.objects.filter(Q(name__contains=query) | Q(mobile__contains=query))
            customer_dict = {}
            for each in all_cust:
                customer_dict[each.id] = {
                    'name': each.name,
                    'mobile': each.mobile
                }
            return HttpResponse(json.dumps(customer_dict))
        else:
            return HttpResponse('Error:Null query')
    else:
        return HttpResponse('Error:Not ajax')


def get_reports(request):
    return render(request, 'reports.html')


def customer_registration(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        mobile = request.POST.get('mobile')
        email = request.POST.get('email')
        address = request.POST.get('address')

        cust_obj = Customer.objects.create(name=name, email=email, mobile=mobile, address=address)

        return HttpResponse('Successfully registered')
    else:
        return HttpResponse('Not Post')


def new_order(request, customer_id):
    c_id = int(customer_id)
    customer_obj = Customer.objects.filter(id=c_id)
    cats = Category.objects.filter(is_active=True).values_list('name', flat=True)
    if len(customer_obj) == 1:
        customer_obj = customer_obj[0]

        if request.method == 'POST':
            kg = float(request.POST.get('kg'))
            price_json = OrderedDict()
            all_price = Price.objects.all().order_by('kg')
            for each_price in all_price:
                price_json[str(each_price.kg)] = each_price.cost
            price_json = OrderedDict(sorted(price_json.items()))
            if kg < 0:
                return render(request, 'new_order.html', {
                    'customer_obj': customer_obj,
                    'price_json': json.dumps(price_json),
                    'message_title': 'Error',
                    'message_type': 'error',
                    'message': 'Kg should be greater than 0',
                    'category': [cats[i:i + 2] for i in range(0, len(cats), 2)]
                })
            # current_price = Price.objects.order_by('-kg').filter(kg__lte=kg)[:1][0]
            current_price = float(request.POST.get('price'))
            print(current_price)
            order_obj = Order(customer=customer_obj, kg=kg, received_date=datetime.datetime.now(),
                              price=current_price, status=1)

            order_obj.save()

            if request.POST.get('selected') == 'ind_kg':
                for each in request.POST:
                    if each.__contains__('cloth_'):
                        each_id = each.split('cloth_')[1]
                        cat_obj = Category.objects.get_or_create(name=request.POST.get(each), is_active=True)[0]
                        order_details = OrderDetail(order=order_obj, category=cat_obj,
                                                    count=int(request.POST.get('qty_' + each_id)))
                        order_details.save()

                order_obj.status = 2
                order_obj.save()
            return render(request, 'new_order.html', {
                'customer_obj': customer_obj,
                'price_json': json.dumps(price_json),
                'message_type': 'success',
                'message_title': 'Success',
                'swal_redirect': '/',
                'message': 'Order registered for customer ' + customer_obj.name,
                'category': [cats[i:i + 2] for i in range(0, len(cats), 2)]
            })
        else:
            all_price = Price.objects.all().order_by('kg')
            price_json = {}
            for each_price in all_price:
                price_json[str(each_price.kg)] = each_price.cost

            return render(request, 'new_order.html', {
                'customer_obj': customer_obj,
                'price_json': json.dumps(price_json),
                'category': [cats[i:i + 2] for i in range(0, len(cats), 2)]
            })
    else:
        return HttpResponse('No objects found with that id')


def orders(request):
    orders = Order.objects.filter(is_active=True).order_by('-pk')
    return render(request, 'orders.html', {'orders': orders})


def excel_download_response(file_path, file_name, data):
    file_mimetype = mimetypes.guess_type(file_path)
    response = HttpResponse(data, content_type=file_mimetype)
    response['X-Sendfile'] = file_path
    response['Content-Length'] = os.stat(file_path).st_size
    response['Content-Disposition'] = 'attachment; filename=%s' % smart_str(file_name)
    return response


def day_excel(request):
    if request.method == 'POST':
        cur_date = request.POST.get('daterange')
        date = datetime.datetime.strptime(cur_date, '%d-%m-%Y').date()
        print(cur_date)
        print(date)
        day, month, year = date.day, date.month, date.year
        received_orders = Order.objects.filter(received_date__year=year, received_date__month=month,
                                               received_date__day=day)

        delivered_orders = Order.objects.filter(delivery_date__year=year, delivery_date__month=month,
                                                delivery_date__day=day)

        wb = Workbook()

        sheet_received_name = 'Received'
        sheet_delivered_name = 'Delivered'

        if sheet_delivered_name in wb:
            wb.remove(wb[sheet_delivered_name])
        if sheet_received_name in wb:
            wb.remove(wb[sheet_received_name])

        file_name = date.strftime('%d-%m-%Y') + '.xlsx'
        work_sheet_received = wb.active
        work_sheet_received.title = 'Received'
        heading_received = ['Order Number', 'Customer', 'Price', 'kg']
        work_sheet_received.append(heading_received)

        for each_order in received_orders:
            temp = [each_order.pk, each_order.customer.name, each_order.price, each_order.kg]
            work_sheet_received.append(temp)
        # wb.save('media/' + file_name)

        heading_delivered = ['Order Number', 'Customer', 'Price', 'kg', 'Received Date']

        work_sheet_delivered = wb.create_sheet(title=sheet_delivered_name)
        # work_sheet.title = 'Received'
        work_sheet_delivered.append(heading_delivered)

        for each_order in delivered_orders:
            # cur_status = 'Not Delivered'
            # if each_order.status == 4:
            #     cur_status = 'Delivered'
            temp = [each_order.pk, each_order.customer.name, each_order.price, each_order.kg,
                    each_order.received_date.strftime('%d-%m-%Y')]
            work_sheet_delivered.append(temp)

        # work_sheet.append([random.randint(5, 10)])
        file_path = os.path.join(MEDIA_ROOT, file_name)
        wb.save(file_path)

        with open(file_path, "rb") as excel:
            data = excel.read()
            excel.close()

home/templates/base.html
{% load static %}
<script src="{% static 'home/js/jquery.min.js' %}"></script>
<link href="{% static 'home/css/bootstrap.css' %}" rel="stylesheet" id="bootstrap-css">
<script src="{% static 'home/js/bootstrap.min.js' %}"></script>
{#<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">#}
{#<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>#}
<!------ Include the above in your HEAD tag ---------->

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description"
          content="Responsive sidebar template with sliding effect and dropdown menu based on bootstrap 3">
    <title>Wool World</title>

    {#    <link href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" rel="stylesheet">#}
    <link href="{% static 'home/fonts/fontawesome-free-5.5.0-web/css/all.css' %}" rel="stylesheet" id="bootstrap-css">

    <link rel="stylesheet" href="{% static 'home/css/test.css' %}">

    <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.3.0/css/datepicker.css" rel="stylesheet"
          type="text/css"/>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.3.0/js/bootstrap-datepicker.js"></script>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
</head>

<body>

<nav class="navbar navbar-expand-sm navbar-light bg-light justify-content-end fixed-top">
    <a class="navbar-brand" href="{% url 'home:home_page' %}">
        {#                <img src="/images/logo/QuickWash-navbar.svg" width="30" height="30" class="d-inline-block align-top">#}
        {#        <img src="" width="30" height="30" class="glyphicon glyphicon-magnet">#}

        <i class="material-icons">local_drink</i>
        <span>Wool World</span>
    </a>
    <div class="collapse navbar-collapse mr-auto" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item active mr-auto navbar-right">
                <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item navbar-right">
                <a class="nav-link" href="#">Reciept</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown"
                   aria-haspopup="true" aria-expanded="false">
                    Reports
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                    <a class="dropdown-item" href="#">Daily</a>
                    <a class="dropdown-item" href="#">Monthly</a>
                    <a class="dropdown-item" href="#">Quaterly</a>
                </div>
            </li>
        </ul>
    </div>
</nav>


<div class="page-wrapper chiller-theme toggled">
    <a id="show-sidebar" class="btn btn-sm btn-dark" href="#">
        <i class="fas fa-bars"></i>
    </a>
    <nav id="sidebar" class="sidebar-wrapper">
        <div class="sidebar-content">

            {#            <div class="sidebar-header">#}
            {#                <div class="user-pic">#}
            {#                    <img class="img-responsive img-rounded"#}
            {#                         src="https://raw.githubusercontent.com/azouaoui-med/pro-sidebar-template/gh-pages/src/img/user.jpg"#}
            {#                         alt="User picture">#}
            {#                </div>#}
            {#                <div class="user-info">#}
            {#          <span class="user-name">Jhon#}
            {#            <strong>Smith</strong>#}
            {#          </span>#}
            {#                    <span class="user-role">Administrator</span>#}
            {#                    <span class="user-status">#}
            {#            <i class="fa fa-circle"></i>#}
            {#            <span>Online</span>#}
            {#          </span>#}
            {#                </div>#}
            {#            </div>#}
            <!-- sidebar-header  -->
            <div class="sidebar-search">
                <div>
                    <div class="input-group">
                        <input type="text" class="form-control search-menu" placeholder="Search...">
                        <div class="input-group-append">
              <span class="input-group-text">
                <i class="fa fa-search" aria-hidden="true"></i>
              </span>
                        </div>
                    </div>
                </div>
            </div>
            <!-- sidebar-search  -->
            <div class="sidebar-menu">
                <ul>

                    <li>
                        <a href="{% url 'home:home_page' %}">
                            <i class="fa fa-tachometer-alt"></i>
                            <span>Dashboard</span>
                        </a>
                    </li>
                    <li class="sidebar-dropdown">
                        <a href="#">
                            <i class="fa fa-chart-line"></i>
                            <span>Excel</span>
                        </a>
                        <div class="sidebar-submenu">
                            <ul>
                                <li>
                                    <a href="{% url 'home:daywise_excel' %}">Day-Wise Orders</a>
                                </li>
                                <li>
                                    <a href="{% url 'home:general_excel' %}">General Excel</a>
                                </li>
                            </ul>
                        </div>
                    </li>
                    <li>
                        <a href="{% url 'home:expenses' %}">
                            <i class="fa fa-folder"></i>
                            <span>Add Expenses</span>
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'home:orders' %}">
                            <i class="fa fa-folder"></i>
                            <span>Show Orders</span>
                        </a>
                    </li>
                </ul>
            </div>
            <!-- sidebar-menu  -->
        </div>
        <!-- sidebar-content  -->
    </nav>
    <!-- sidebar-wrapper  -->
    {% block content %}
    {% endblock content %}

    <!-- page-content" -->
</div>
<!-- page-wrapper -->
{#<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>#}
{#<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"#}
{#        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"#}
{#        crossorigin="anonymous"></script>#}


<script src="{% static 'home/css/test.js' %}"></script>
<script src="{% static 'home/js/popper.js' %}"></script>
<script src="{% static 'home/js/sweet-alert.min.js' %}"></script>

{% block scripts %}

{% endblock scripts %}

<script>
    $(document).ready(function () {
        console.log("{{ message_type }}");
        if ("{{ message_type }}") {
            swal("{{ message_title }}", "{{ message }}", '{{ message_type }}');
        }
    });

    {% block on_ready %}

    {% endblock on_ready %}

</script>


</body>

</html>

home/templates/home.html
{% extends 'base.html' %}
{#<body>#}
{% block content %}

    {#    <form>#}
    <main class="page-content">
        <div class="container-fluid">
            <div class="row">
                <div class="form-group col-md-12">
                    <div class="sidebar-search" style="width: 50% !important;">
                        <div>
                            <div id="livesearch" class="input-group">

                                <input type="text" class="form-control search-menu" autocomplete="off"
                                       placeholder="Enter Name or Phone number..." id="query">
                                <div class="input-group-append">
                                    <span class="input-group-text">
                                        <i class="fa fa-search" aria-hidden="true"></i>
                                    </span>
                                </div>
                                <div class="col-md-1">
                                    <button class="btn btn-success" data-toggle="modal" data-target="#myModal"><i
                                            class="material-icons">person_add</i>
                                    </button>
                                </div>
                            </div>
                            <!-- Suggestions will be displayed in below div. -->
                            <div id="search-wrap" class="row hidden" style="margin:.5% 0!important;">
                                <div id="live-search-result" class="suggestion-wrap">
                                    <ul></ul>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            </div>

            {% block home_content %}
            {% endblock home_content %}
        </div>
    </main>
    {#    </form>#}

    <div id="myModal" class="modal fade" role="dialog" data-backdrop="static" data-keyboard="false">
        <div class="modal-dialog">

            <!-- Modal content-->
            <form onsubmit="register_request(event);" method="POST">
                {% csrf_token %}
                <div class="modal-content">
                    <div class="modal-header">

                        <h4 class="modal-title">New Customer</h4>
                    </div>
                    <div class="modal-body">
                        <div class="col-md-5">

                            <div class="form-group">
                                <div class="row">
                                    <label for="name">Name *</label>
                                    <input name="name" id="name" required type="text" class="form-control">
                                </div>

                                <div class="row">
                                    <label for="number">Phone Number *</label>
                                    <input name="mobile" id="mobile" required type="number" class="form-control">
                                </div>

                                <div class="row">
                                    <label for="email">Email</label>

                                    <input name="email" id="email" type="email" class="form-control">

                                </div>
                                <div class="row">
                                    <label for="address">Address</label>

                                    <input name="address" id="address" type="text" class="form-control">

                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                        <button type="submit" name="register_btn" class="btn btn-primary">
                            Register
                        </button>
                    </div>
                </div>
            </form>

        </div>
    </div>


{% endblock content %}

{% block scripts %}
    <script>
        $('#live-search-result').on('click', 'li', function () {
            document.location.href = '/new_order/' + this.id + '/';
        })
    </script>

    <script>
        function register_request(e) {
            e.preventDefault();
            let name = document.getElementById('name').value;
            let mobile = document.getElementById('mobile').value;
            let email = document.getElementById('email').value;
            let address = document.getElementById('address').value;
            var saveData = $.ajax({
                type: 'POST',
                url: "{% url 'home:register_customer' %}",

                data: {

                    'csrfmiddlewaretoken': '{{ csrf_token }}',
                    'name': name,
                    'mobile': mobile,
                    'email': email,
                    'address': address
                },
                dataType: "text",
                success: function (resultData) {
                    swal("Success", resultData, 'success');
                    $('#myModal').modal('hide');
                }
            });
            saveData.error(function () {
                swal("Error", "Something went wrong", 'error');
            });
        }
    </script>

    <script>
        $(document).on('input', '.search-menu', function () {

            console.log('Function called');
            $("#live-search-result").css('visibility', 'visible');
            let value = this.value;
            console.log(value);
            if (value.length > 0) {
                let obj = document.getElementById('search_query');
                $.ajax({
                    type: "POST",
                    url: '{% url 'home:get_customer' %}',
                    data: {
                        'csrfmiddlewaretoken': '{{ csrf_token }}',
                        'query': value
                    },
                    async: true,
                    success: function (data) {

                        var live_obj = $('.suggestion-wrap ul');
                        {#var div_obj = $('#live-search-result');#}
                        {#div_obj.empty();#}
                        console.log(live_obj);
                        live_obj.empty();
                        console.log(data);
                        live_obj.innerText = '';
                        let customers = JSON.parse(data);
                        for (var key in customers) {
                            console.log(customers[key]['name']);
                            live_obj.append('<li id=' + key + '>' + customers[key]['name'] + ' ' + customers[key]['mobile'] + '</li>');
                        }

                    }
                })
            }

        });
    </script>
    {% block home_script %}
    {% endblock home_script %}

{% endblock scripts %}